services:
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
