# fly.toml app configuration file generated for fincon-backend on 2025-01-30T21:35:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fincon-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  APP_ENV = 'prod'
