name: Backend CD

on:
  push:
    tags:
      - "backend-v*"

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    concurrency: backend-deploy-group    # ensure only one action runs at a time

    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create .env file
        run: echo "${{ secrets.PROD_ENV }}" > .prod.env

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
