name: Backend CD

on:
  push:
    branches: [main]
    paths: 
      - 'backend/**'
      - '.github/workflows/backend-cd.yml'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # ensure only one action runs at a time

    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create .env file
        run: printf "%s" "${{ secrets.PROD_ENV }}" > .prod.env

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
