name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v6.3.1

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-mod-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}

      - name: Install dependencies
        run: go mod tidy

      - name: Setup DB
        run: |
          make setup-db
          make migrate
        env:
          APP_ENV: test

      - name: Run tests
        run: make test
        env:
          APP_ENV: test

      - name: Build project 
        run: make build
